### ISSUE TITLE
aboute Manifest V3

### ISSUE THREAD

**Issue by hsinyu-chen** [CommanderAnime/CommanderAnime#1]
I see your comment on the tampermonkey repo , because I try to find thread to discuss Manifest V3  effect to extensions need user script just Literally like you

I find the last answer of `append script tag` trick idk if its working but in my case , I use monaco editor as my script editor in my extension UI , and I check the monaco repo , and it use `eval` with no surprise.

so I came to here to ask if you got any update/news on this ?

**Comment by asger-finding** [comment]
Yes! I've decided to inject a script tag and override eval in said script tag.
Source code for my MV3 extension will be up on [My TankTroubleAddons Repo](https://github.com/CommanderAnime/TankTroubleAddons) when I get some more work done on it.

Note that script injecting at `document_start` is currently terribly buggy, and it loads incorrectly if the script is a module. I have brought the issue up on StackOverflow [here](https://stackoverflow.com/questions/70566518/injected-script-doesnt-run-correctly-unless-cache-is-cleared).

These chrome reports may be of help:
[Dynamic content script support](https://crbug.com/1054624)
[MV3 content scripts need to add js in main world synchronously](https://crbug.com/1207006)

**Comment by hsinyu-chen** [comment]
thanks , but the extension I created is like tampermonkey  but with vscode(monano) in the editing UI and can compile ts/scss.
if I still want to use the fancy code editor in extension to edit user script ,I need to inject the fat lib into every site and
build whole extension interface in every site make me concern about performance,
I see some ppl say google still want support power user to use user script in the extension , but I can't find any additional info for that ,  I guess I can only wait few more quater hope there is something we can use.

**Comment by asger-finding** [comment]
No conclusion reached, closing issue
